name: fitwiz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: any
  carousel_slider: ^5.0.0
  dio: ^5.6.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  jwt_decoder: ^2.0.1
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  timelines: ^0.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path_android: "assets/logo/logo_fg_android.png"
  adaptive_icon_background: "#621DBF"
  adaptive_icon_foreground: "assets/logo/logo_fg_android.png"
  adaptive_icon_monochrome: "assets/logo/logo_fg_android.png"
  
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo/logo_ios.png"
  desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/logo/logo_ios.png"
    background_color: "#FFFFFF"
    theme_color: "#621DBF"
